In [2]:
import numpy as np

data = np.genfromtxt("HenrysForkDischarge.csv", delimiter=',')


In [3]:
print(data)

[[             nan              nan              nan              nan]
 [  2.00000000e+03   1.00000000e+01   1.00000000e+00   3.93618527e+01]
 [  2.00000000e+03   1.00000000e+01   2.00000000e+00   3.93618527e+01]
 ..., 
 [  2.01500000e+03   9.00000000e+00   2.80000000e+01   2.42684228e+01]
 [  2.01500000e+03   9.00000000e+00   2.90000000e+01   2.44949659e+01]
 [  2.01500000e+03   9.00000000e+00   3.00000000e+01   2.45516016e+01]]
